In [10]:
import numpy as np

mulai = int(input("Mulai: "))
selesai = int(input("Selesai: "))

#Create array 1D
arr = np.arange(mulai,selesai,1) # (start, stop, step)
arr1 = np.array(arr)
print(arr1)

Mulai: 1
Selesai: 28
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]


In [12]:
#Create array 2D
b = arr1.reshape(3,9) #KPK dari 27
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [27]:
#Create array 3D
c = arr1.reshape(3,3,3) #KPK dari 27
c

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [33]:
import numpy as np
n = int(input("Banyak Data : "))
mulai = int(input("Mulai : "))
selesai = int(input("Selesai : "))


Banyak Data : 16
Mulai : 1
Selesai : 50


In [35]:
data = np.random.randint(mulai, selesai, n)
data

array([19, 49, 15, 25,  2, 25, 48, 40, 42, 31, 39, 36, 39,  2, 41,  6])

In [36]:
#Create array 1D
print('Array 1D:')
print(data)

Array 1D:
[19 49 15 25  2 25 48 40 42 31 39 36 39  2 41  6]


In [41]:
# Create array 2D
arr2 = data.reshape(4,4)
arr2

array([[19, 49, 15, 25],
       [ 2, 25, 48, 40],
       [42, 31, 39, 36],
       [39,  2, 41,  6]])

In [42]:
# Create array 3D
print('Tukar Posisi:')
tukar = arr2[:, ::-1]
tukar

Tukar Posisi:


array([[25, 15, 49, 19],
       [40, 48, 25,  2],
       [36, 39, 31, 42],
       [ 6, 41,  2, 39]])

In [39]:
# Array 2D 10x10
x = np.ones((10,10))*4
x[1:-1,1:-1] = 0
print (x)

[[4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]]
